import { LanguageOption } from "./types";

export const SUPPORTED_LANGUAGES: LanguageOption[] = [
  { code: "en", name: "English" },
  { code: "es", name: "Spanish (Español)" },
  { code: "fr", name: "French (Français)" },
  { code: "de", name: "German (Deutsch)" },
  { code: "it", name: "Italian (Italiano)" },
  { code: "pt", name: "Portuguese (Português)" },
  { code: "ru", name: "Russian (Русский)" },
  { code: "zh", name: "Chinese Simplified (简体中文)" },
  { code: "zh-TW", name: "Chinese Traditional (繁體中文)" },
  { code: "ja", name: "Japanese (日本語)" },
  { code: "ko", name: "Korean (한국어)" },
  { code: "ar", name: "Arabic (العربية)" },
  { code: "hi", name: "Hindi (हिन्दी)" },
  { code: "bn", name: "Bengali (বাংলা)" },
  { code: "tr", name: "Turkish (Türkçe)" },
  { code: "vi", name: "Vietnamese (Tiếng Việt)" },
  { code: "pl", name: "Polish (Polski)" },
  { code: "nl", name: "Dutch (Nederlands)" },
  { code: "sv", name: "Swedish (Svenska)" },
  { code: "no", name: "Norwegian (Norsk)" },
  { code: "da", name: "Danish (Dansk)" },
  { code: "fi", name: "Finnish (Suomi)" },
  { code: "el", name: "Greek (Ελληνικά)" },
  { code: "he", name: "Hebrew (עברית)" },
  { code: "id", name: "Indonesian (Bahasa Indonesia)" },
  { code: "th", name: "Thai (ไทย)" },
  { code: "uk", name: "Ukrainian (Українська)" },
  { code: "cs", name: "Czech (Čeština)" },
  { code: "ro", name: "Romanian (Română)" },
  { code: "hu", name: "Hungarian (Magyar)" },
  { code: "ms", name: "Malay (Bahasa Melayu)" },
  { code: "fa", name: "Persian (فارسی)" },
  { code: "tl", name: "Tagalog / Filipino" },
  { code: "ta", name: "Tamil (தமிழ்)" },
  { code: "te", name: "Telugu (తెలుగు)" },
  { code: "kn", name: "Kannada (ಕನ್ನಡ)" },
  { code: "ml", name: "Malayalam (മലയാളം)" },
  { code: "gu", name: "Gujarati (ગુજરાતી)" },
  { code: "mr", name: "Marathi (मराठी)" },
  { code: "pa", name: "Punjabi (ਪੰਜਾਬੀ)" },
  { code: "ur", name: "Urdu (اردو)" },
  { code: "sw", name: "Swahili (Kiswahili)" },
  { code: "af", name: "Afrikaans" },
  { code: "am", name: "Amharic (አማርኛ)" },
  { code: "hy", name: "Armenian (Հայերեն)" },
  { code: "az", name: "Azerbaijani (Azərbaycanca)" },
  { code: "bg", name: "Bulgarian (Български)" },
  { code: "ca", name: "Catalan (Català)" },
  { code: "hr", name: "Croatian (Hrvatski)" },
  { code: "eo", name: "Esperanto" },
  { code: "et", name: "Estonian (Eesti)" },
  { code: "ka", name: "Georgian (ქართული)" },
  { code: "is", name: "Icelandic (Íslenska)" },
  { code: "ga", name: "Irish (Gaeilge)" },
  { code: "la", name: "Latin (Latina)" },
  { code: "lv", name: "Latvian (Latviešu)" },
  { code: "lt", name: "Lithuanian (Lietuvių)" },
  { code: "mk", name: "Macedonian (Македонски)" },
  { code: "mt", name: "Maltese (Malti)" },
  { code: "ne", name: "Nepali (नेपाली)" },
  { code: "sk", name: "Slovak (Slovenčina)" },
  { code: "sl", name: "Slovenian (Slovenščina)" },
  { code: "sr", name: "Serbian (Српски)" },
  { code: "si", name: "Sinhala (සිංහල)" },
  { code: "so", name: "Somali (Soomaali)" },
  { code: "cy", name: "Welsh (Cymraeg)" },
  { code: "yo", name: "Yoruba (Yorùbá)" },
  { code: "zu", name: "Zulu (isiZulu)" },
  { code: "mi", name: "Maori (Māori)" },
  { code: "km", name: "Khmer (ខ្មែរ)" },
  { code: "lo", name: "Lao (ລາວ)" },
];
